apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  volumes:
  - name: podvolume
    persistentVolumeClaim:
      claimName: pvc-practice 
  containers:
  - image: nginx
    name:  nginx-container
    ports: 
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: podvolume