apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
spec:
  azureFile:
    secretName: pv-rajnish-aks
    shareName: akspvfile
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pvtopvcbound