apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-practice
  namespace: default
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: pvtopvcbound