apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-ns
  namespace: default
  labels:
    networkrule: blockaccess
spec:
  containers:
  - image: nginx
    name:  nginx-container
    ports: 
    - containerPort: 80